media:
  input: assets/uploads
  output: /assets/uploads

content:
  - name: entries
    label: Book Reviews
    type: file
    path: content/entries.json
    format: json
    list: true
    fields:
      - name: title
        label: Titel
        type: string
      - name: cover_image
        label: Cover Image
        type: image
      - name: verlag
        label: Verlag
        type: string
      - name: jahr
        label: Jahr
        type: number
      - name: review
        label: Review
        type: rich-text