local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "media"
public_folder: "/media"

collections:
  - name: "blog"
    label: "Blog Entries"
    files:
      - file: "data/entries.json"
        label: "Entries List"
        name: "entries_list"
        fields:
          - label: "Entries"
            name: "entries"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "URL Slug", name: "slug", widget: "string", hint: "Unique ID, e.g., house-in-zurich" }
              - { label: "Year", name: "year", widget: "number", value_type: "int" }
              - { label: "Cover Image", name: "cover_image", widget: "image" }
              - { label: "Short Summary", name: "description", widget: "text" }
              - { label: "Full Body Text", name: "full_description", widget: "markdown", required: false }